shape: sequence_diagram
Painter -> Jeeves: connect
Jeeves -> Painter: WHO_ARE_YOU
Painter -> Jeeves: painter
Jeeves -> Painter: BUFFER_SIZE
Jeeves -> Painter: SEND_ME_PIXELS
Painter -> Jeeves: PIXELS
